project:
  type: website
  output-dir: _site

website:
  title: "STT-1100 Introduction à la science des données"
  sidebar:
    style: "floating"
    contents:
      - text: "Accueil"
        href: index.qmd
      - section: "Modules"
        contents:
          - section: "1 - Plongée en science des données"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 1 /1 - Plan d'apprentissage.qmd"
              - text: "Aventure"
                href: "Module 1 /1 - Aventure/Aventure 1.qmd"
              - text: "Défi"
                href: "Module 1 /1 - défi/1 - Défi Plongée en science des données.qmd"
          - section: "2 - GitHub et visualisation de données"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 2/2 - Plan d'apprentissage.qmd"
              - text: "Aventure"
                href: "Module 2/2 - Aventure/Aventure 2.qmd"
              - text: "Défi"
                href: "Module 2/2 - défi/2 - Défi.qmd"
          - section: "3 - Les catégories sous toutes leurs formes"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 3/3 - Plan d'apprentissage.qmd"
              - text: "Aventure"
                href: "Module 3/3 - Aventure/Aventure 3.qmd"
              - text: "Défi"
                href: "Module 3/3 - défi/3 - Défi.qmd"
          - section: "4 - Facteurs et nettoyage de données"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 4/4 - Plan d'apprentissage.qmd"
              - text: "Aventure"
                href: "Module 4/Aventure/Aventure 4.qmd"
          - section: "5 - Explorer et comprendre les relations entre les variables"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 5/plan d'apprentissage module 5.qmd"
              - text: "Aventure"
                href: "Module 5/aventure/Aventure 5.qmd"
          - section: "6 - Collaboration et reproductibilité dans GitHub"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 6/Plan d'apprentissage module 6.qmd"
              - text: "Aventure"
                href: "Module 6/Aventure/Aventure 6.qmd"
          - section: "7 - Visualisation, éthique et sécurisation des données"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 7/Plan d'apprentissage module 7.qmd"
              - text: "Aventure"
                href: "Module 7/Aventure/Aventure 7.qmd"
          - section: "8 - Automatisation et exploration du web"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 8/Plan d'apprentissage module 8.qmd"
              - text: "Aventure"
                href: "Module 8/Aventure/Aventure 8.qmd"
          - section: "9 - Prédiction et biais"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 9/Plan d'apprentissage module 9.qmd"
              - text: "Aventure"
                href: "Module 9/Aventure/Aventure 9.qmd"
          - section: "10 - Au-delà des données : texte et tableau de bord"
            contents:
              - text: "Plan d'apprentissage"
                href: "Module 10/Plan d'apprentissage module 10.qmd"
              - text: "Aventure"
                href: "Module 10/Aventure/Aventure 10.qmd"
      - text: "Matériel de référence"
        href: references.qmd
format:
  html:
    include-after-body: toggle-sidebar.html
