---
title: "Memo - Clone a GitHub project in RStudio"
format:
  html:
    toc: true
    toc-depth: 2
    theme: cosmo
    highlight-style: github
    embed-resources: true
    code-tools: true
    page-layout: full
---


## Preparation

You must have installed:

- R
- RStudio
- Git (confirm that a path appears under `Tools > Global Options > Git/SVN`)
- A GitHub account

Before cloning your first repository, follow [Connect GitHub to RStudio with SSH](connexion-ssh-github-rstudio.qmd). It mainly uses RStudio and GitHub menus and buttons.

Never use your GitHub password directly to clone, push or pull a repository.

---

## Find the GitHub project link

1. Go to the page of the GitHub repository you want to clone.
2. Click on the green `<> Code` button.
3. Choose the SSH tab when possible, then copy the displayed link.
4. If the SSH tab is unavailable, confirm that you accepted the repository invitation.

Examples:

- SSH: `git@github.com:UserName/project-name.git`

---

## Clone in RStudio

1. Open RStudio.
2. Go to `File > New Project`.
3. Choose `Version Control`.
4. Select `Git`.
5. Paste the copied link into the `Repository URL` field.
6. Choose a local folder to save the project
7. Click on `Create Project`.

 It’s done! You can start working in your new RStudio project.

---

## GitHub authentication error

If you get this error:

```
fatal: Authentication failed
remote: Support for password authentication was removed...
```

This usually means that you copied the HTTPS link instead of the SSH link. Return to the repository page, click `<> Code`, choose `SSH`, and copy that link.

If SSH is not configured yet or the message contains `Permission denied (publickey)`, follow the [button-based SSH procedure](connexion-ssh-github-rstudio.qmd).

---

## Useful resources

- [SSH connection between GitHub and RStudio](connexion-ssh-github-rstudio.qmd)
- [Version control in RStudio (Posit)](https://docs.posit.co/ide/user/ide/guide/tools/version-control.html)
- [Configure SSH GitHub (Official)](https://docs.github.com/en/authentication/connecting-to-github-with-ssh)

---

Happy programming!
