name: Publish Quarto site to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write   # nécessaire pour pousser sur gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "stable"

      # (Optionnel) Installe TinyTeX si le projet rend des PDF
      # - name: Setup TinyTeX
      #   uses: r-lib/actions/setup-tinytex@v2

      - name: Render site
        run: quarto render

      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
